apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"443":"svc-backend"}}'
    cloud.google.com/neg: '{"ingress":true}'
    networking.gke.io/v1beta1.FrontendConfig: svc-frontend
  labels:
    app: ghost-app
  name: ghost-app-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30901
    port: 80
    protocol: TCP
    targetPort: 2368
  selector:
    app: ghost-app
  sessionAffinity: None
  type: LoadBalancer
